"""Deterministic weather model definitions and variables."""

DETERMINISTIC_MODELS = [
    {
        "group": "Seamless",
        "items": [
            {"label": "Best Match 🌍", "value": "best_match"},
            {"label": "ICON Seamless 🌍", "value": "icon_seamless"},
            {"label": "GFS Seamless 🌍", "value": "gfs_seamless"},
            {"label": "MeteoFrance Seamless 🌍", "value": "meteofrance_seamless"},
            {"label": "ICON-CH Seamless 🇨🇭", "value": "meteoswiss_icon_seamless"},
            {"label": "JMA Seamless 🌍", "value": "jma_seamless"},
            {"label": "GEM Seamless 🌍", "value": "gem_seamless"},
            {"label": "UKMO Seamless 🌍", "value": "ukmo_seamless"},
        ],
    },
    {
        "group": "Global",
        "items": [
            {"label": "ICON Global (🌍, 11km)", "value": "icon_global"},
            {"label": "IFS (🌍, 9km)", "value": "ecmwf_ifs"},
            {"label": "AIFS single (🌍, 25km)", "value": "ecmwf_aifs025_single"},
            {"label": "GFS (🌍, 25/13km)", "value": "gfs_global"},
            {"label": "AIGFS (🌍, 25km)", "value": "ncep_aigfs025"},
            {"label": "HGEFS (🌍, 25km)", "value": "ncep_hgefs025_ensemble_mean"},
            {"label": "Arpege (🌍, 55km)", "value": "meteofrance_arpege_world"},
            {"label": "UKMO (🌍, 10km)", "value": "ukmo_global_deterministic_10km"},
            {"label": "GSM (🌍, 55km)", "value": "jma_gsm"},
            {"label": "CMA GRAPES (🌍, 15km)", "value": "cma_grapes_global"},
            {"label": "GEM Global (🌍, 15km)", "value": "gem_global"},
            {"label": "ACCESS-G (🌍, 15km)", "value": "bom_access_global"},
        ],
    },
    {
        "group": "Regional (🇪🇺)",
        "items": [
            {"label": "ICON-EU (🇪🇺, 7km)", "value": "icon_eu"},
            {"label": "MeteoFrance Arpege (🇪🇺, 11km)", "value": "meteofrance_arpege_europe"},
            {"label": "DMI Harmonie (🇪🇺, 2km)", "value": "dmi_harmonie_arome_europe"},
            {
                "label": "KNMI Harmonie (🇪🇺, 5.5km)",
                "value": "knmi_harmonie_arome_europe",
            },
            {"label": "CHMI Aladin (🇪🇺, 2km)", "value": "chmi_aladin_central_europe_2km"},
            {"label": "ICON-D2 (🇩🇪, 2km)", "value": "icon_d2"},
            {"label": "Geosphere AROME (🇦🇹, 2.5km)", "value": "geosphere_arome_austria"},
            {"label": "ICON-CH1 (🇨🇭, 1km)", "value": "meteoswiss_icon_ch1"},
            {"label": "ICON-CH2 (🇨🇭, 2km)", "value": "meteoswiss_icon_ch2"},
            {"label": "MetNo (🇳🇴🇸🇪🇫🇮, 1km)", "value": "metno_nordic"},
            {
                "label": "KNMI Harmonie (🇳🇱, 2km)",
                "value": "knmi_harmonie_arome_netherlands",
            },
            {"label": "Arpege (🇫🇷, 2.5km)", "value": "meteofrance_arome_france"},
            {"label": "Arpege HD (🇫🇷, 1.5km)", "value": "meteofrance_arome_france_hd"},
            {"label": "ICON-2I (🇮🇹, 2km)", "value": "italia_meteo_arpae_icon_2i"},
            {"label": "UKMO (🇬🇧, 2km)", "value": "ukmo_uk_deterministic_2km"},
            {"label": "CHMI Aladin (🇨🇿, 1km)", "value": "chmi_aladin_cz_1km"},
        ],
    },
    {
        "group": "Regional (others)",
        "items": [
            {"label": "HRRR (🇺🇸, 3km)", "value": "gfs_hrrr"},
            {"label": "NBM (🇺🇸, 2.5km)", "value": "ncep_nbm_conus"},
            {"label": "NAM (🇺🇸, 3km)", "value": "ncep_nam_conus"},
            {"label": "MSM (🇯🇵, 5km)", "value": "jma_msm"},
            {"label": "GEM Regional (🇺🇸, 10km)", "value": "gem_regional"},
            {"label": "HRDPS (🇨🇦, 2.5km)", "value": "gem_hrdps_continental"},
            {"label": "HRDPS West (🇨🇦, 1km)", "value": "gem_hrdps_west"},
        ],
    },
]

DETERMINISTIC_VARS = [
    {
        "group": "Instantaneous",
        "items": [
            {"label": "2m Temperature", "value": "temperature_2m"},
            {"label": "850hPa Temperature", "value": "temperature_850hPa"},
            {"label": "850hPa Relative Humidity", "value": "relative_humidity_850hPa"},
            {"label": "850hPa geopotential", "value": "geopotential_height_850hPa"},
            {"label": "500hPa Temperature", "value": "temperature_500hPa"},
            {"label": "500hPa Relative Humidity", "value": "relative_humidity_500hPa"},
            {"label": "500hPa geopotential", "value": "geopotential_height_500hPa"},
            {"label": "250hPa Temperature", "value": "temperature_250hPa"},
            {"label": "250hPa geopotential", "value": "geopotential_height_250hPa"},
            {"label": "100hPa Temperature", "value": "temperature_100hPa"},
            {"label": "100hPa geopotential", "value": "geopotential_height_100hPa"},
            {"label": "50hPa Temperature", "value": "temperature_50hPa"},
            {"label": "50hPa geopotential", "value": "geopotential_height_50hPa"},
            {"label": "30hPa Temperature", "value": "temperature_30hPa"},
            {"label": "30hPa geopotential", "value": "geopotential_height_30hPa"},
            {"label": "2m Dew Point", "value": "dew_point_2m"},
            {"label": "Apparent Temperature", "value": "apparent_temperature"},
            {"label": "2m Relative Humidity", "value": "relative_humidity_2m"},
            {"label": "Total Cloud Cover", "value": "cloudcover"},
            {"label": "Low Cloud Cover", "value": "cloud_cover_low"},
            {"label": "Mid Cloud Cover", "value": "cloud_cover_mid"},
            {"label": "High Cloud Cover", "value": "cloud_cover_high"},
            {"label": "Freezing level", "value": "freezing_level_height"},
            {"label": "Snow depth", "value": "snow_depth"},
            {"label": "10m Wind Speed", "value": "wind_speed_10m"},
            {"label": "10m Wind Direction", "value": "wind_direction_10m"},
            {"label": "120m Wind Speed", "value": "wind_speed_120m"},
            {"label": "120m Wind Direction", "value": "wind_direction_120m"},
            {"label": "MSL Pressure", "value": "pressure_msl"},
            {"label": "Convective Available Potential Energy", "value": "cape"},
            {"label": "Visibility", "value": "visibility"},
            {"label": "Surface Temperature", "value": "surface_temperature"},
            {"label": "Weather", "value": "weather_code"},
            {
                "label": "Column Integrated Water Vapour",
                "value": "total_column_integrated_water_vapour",
            },
            {"label": "Lifted Index", "value": "lifted_index"},
            {"label": "Convective Inhibition", "value": "convective_inhibition"},
            {"label": "Boundary Layer Height", "value": "boundary_layer_height"},
            {
                "label": "Precipitation Probability",
                "value": "precipitation_probability",
            },
            {"label": "Soil Temperature (0 cm)", "value": "soil_temperature_0cm"},
            {"label": "Soil Temperature (6 cm)", "value": "soil_temperature_6cm"},
            {"label": "Soil Temperature (18 cm)", "value": "soil_temperature_18cm"},
            {"label": "Soil Temperature (54 cm)", "value": "soil_temperature_54cm"},
            {"label": "Soil Moisture (0-1 cm)", "value": "soil_moisture_0_to_1cm"},
            {"label": "Soil Moisture (1-3 cm)", "value": "soil_moisture_1_to_3cm"},
            {"label": "Soil Moisture (3-9 cm)", "value": "soil_moisture_3_to_9cm"},
            {"label": "Soil Moisture (9-27 cm)", "value": "soil_moisture_9_to_27cm"},
            {"label": "Soil Moisture (27-81 cm)", "value": "soil_moisture_27_to_81cm"},
        ],
    },
    {
        "group": "Accumulated",
        "items": [
            {"label": "Rain", "value": "rain"},
            {"label": "Showers", "value": "showers"},
            {"label": "Snowfall", "value": "snowfall"},
            {"label": "Precipitation", "value": "precipitation"},
            {"label": "Sunshine duration", "value": "sunshine_duration"},
            {
                "label": "Accumulated precipitation (total)",
                "value": "accumulated_precip",
            },
            {
                "label": "Accumulated precipitation (liquid)",
                "value": "accumulated_liquid",
            },
            {"label": "Accumulated precipitation (solid)", "value": "accumulated_snow"},
        ],
    },
    {
        "group": "Preceding hour maximum",
        "items": [
            {"label": "10m Wind Gusts", "value": "windgusts_10m"},
        ],
    },
]
